[variables]
NPM_CONFIG_UPDATE_NOTIFIER = 'false'
NPM_CONFIG_FUND = 'false'

[phases.build]
# Install dependencies and build the project
cmds = [
  "npm install",
  "npm run build",
  "ls dist"  # Verify that dist is created and populated
]

[phases.caddy]
# Ensure Caddy is installed from a compatible Nixpkgs version
dependsOn = ['build']
nixpkgsArchive = 'ba913eda2df8eb72147259189d55932012df6301'
nixPkgs = ['caddy']

[phases.fmt]
# Format the Caddyfile (optional step, useful for debugging)
dependsOn = ['caddy']
cmds = ['caddy fmt --overwrite Caddyfile']

[start]
# Start Caddy using the Caddyfile configuration
cmd = 'caddy run --config Caddyfile --adapter caddyfile'
